# Generated by Django 5.0.1 on 2024-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_form_created_at_question_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='voteCount',
            field=models.IntegerField(default=0),
        ),
    ]
