# Generated by Django 5.0.1 on 2024-04-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_answeroption_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answerText',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
