# Generated by Django 5.0.1 on 2024-04-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_question_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerOption_list', to='backend.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answerType',
            field=models.CharField(choices=[('multiple_choice', 'radio'), ('text', 'text')], max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_list', to='backend.form'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Default', 'Default')], max_length=30),
        ),
    ]
