# Generated by Django 5.0.1 on 2024-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_answeroption_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answerType',
            field=models.CharField(choices=[('1', 'radio'), ('2', 'text')], max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Default')], max_length=30),
        ),
    ]
