# Generated by Django 5.0.3 on 2024-05-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_form_active_alter_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
