# Generated by Django 5.0.3 on 2024-05-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_question_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answerType',
            field=models.CharField(choices=[('0', 'text'), ('1', 'radio')], max_length=300),
        ),
    ]
