# Generated by Django 5.0.3 on 2024-05-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_question_answertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='title',
        ),
    ]
