# Generated by Django 5.0.3 on 2024-05-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_answeroption_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answerType',
            new_name='type',
        ),
    ]
