# Generated by Django 5.0.3 on 2024-05-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_rename_answertype_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='answerOption',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[(0, 'text'), (1, 'radio')], max_length=300),
        ),
    ]
