# Generated by Django 5.0.3 on 2024-05-13 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_userreview_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.profile'),
        ),
    ]
