# Generated by Django 5.0.1 on 2024-03-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0003_aluno_grupo_aluno_maxvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='voteCounter',
            field=models.IntegerField(default=0),
        ),
    ]
