# Generated by Django 5.0.1 on 2024-04-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0004_aluno_votecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='hasPicture',
            field=models.BooleanField(default=False),
        ),
    ]
